### ISSUE TITLE
Feature Request: Enable Voltage Control

### ISSUE THREAD

**Issue by kaseiwang** [kerneltoast/android_kernel_oneplus_msm8974#6]

**Comment by kaseiwang** [comment]
I have create a pull request. It works on my oneplus one.
Please review it if you have time. Thanks :)

**Comment by Tajnymag** [comment]
Are you sure this is a necessity? As I know, sultan tries to keep the ROM as close to stock as possible...

**Comment by kaseiwang** [comment]
Well, it do help me to save battery life. And I use Sultan's ROM for
battery-saving. So I think this will help.
Anyway, let Sultan decided.
